version: "3.7"
services:
  home.addtional-task.server:
    image: nginx:alpine
    container_name: home.addtional-task.server
    working_dir: /app
    volumes:
      - ./:/app
      - ./.dev/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8000:80'
    environment:
      - VIRTUAL_HOST=addtional-task.loc
    networks:
      - default
      - reverse-proxy

  home.addtional-task.fpm:
    image: ruslandev89/php74-fpm-bitrix
    container_name: home.addtional-task.fpm
    working_dir: /app
    volumes:
      - ./:/app
      - ./.dev/php/php.ini:/etc/php/7.4/fpm/php.ini
      - ./.dev/php/php.ini:/etc/php/7.4/cli/php.ini
    networks:
      - default
      - mysql
      - memcached

networks:
  default:
    name: home.addtional-task
  mysql:
    external: true
  memcached:
    external: true
  reverse-proxy:
    external: true
